### ISSUE TITLE
compiling on Linux

### ISSUE THREAD

**Issue by Duality4Y** [il8677/OpenCircuit#1]
Hey there This project looks interesting I read it's configured for windows only so far.
I thought I'd give it a try I had a few errors during compilation which I do not understand for one. the static on a class gave an issue.
second an enum in Job.h gave an issue.
third the libraries were not right for a linux environment.
but after fixing that it runs in as far that a Window appears and a few things are drawn inside but investigating what everything does i soon found out that prety much everything i clicked on generated a Seg Fault.

so here is the diff with the changes I made.

```diff
diff --git a/OpenCircuit/src/Rendering/Renderers/ChunkRenderer.h b/OpenCircuit/src/Rendering/Renderers/ChunkRenderer.h
index 920025a..c22d226 100644
--- a/OpenCircuit/src/Rendering/Renderers/ChunkRenderer.h
+++ b/OpenCircuit/src/Rendering/Renderers/ChunkRenderer.h
@@ -7,7 +7,7 @@ class Window;
 
 class Chunk;
 
-static class ChunkRenderer {
+class ChunkRenderer {
 
 public:
 
diff --git a/OpenCircuit/src/Simulation/Job.h b/OpenCircuit/src/Simulation/Job.h
index 23e7423..911a33f 100644
--- a/OpenCircuit/src/Simulation/Job.h
+++ b/OpenCircuit/src/Simulation/Job.h
@@ -1,6 +1,5 @@
 #pragma once
-
-enum DIR;
+#include "../Utility/vec4.h"
 
 struct Job
 {
diff --git a/premake5.lua b/premake5.lua
index 24f6460..6938385 100644
--- a/premake5.lua
+++ b/premake5.lua
@@ -22,24 +22,25 @@ project "OpenCircuit"
     defines "SFML_STATIC"
 
     links{
-            "opengl32.lib",
-            "freetype.lib",
-            "winmm.lib",
-            "gdi32.lib",
-            "openal32.lib",
-            "flac.lib",
-            "vorbisenc.lib",
-            "vorbisfile.lib",
-            "vorbis.lib",
-            "ogg.lib"
+            "GL"
+            -- "opengl32.lib",
+            -- "freetype.lib",
+            -- "winmm.lib",
+            -- "gdi32.lib",
+            -- "openal32.lib",
+            -- "flac.lib",
+            -- "vorbisenc.lib",
+            -- "vorbisfile.lib",
+            -- "vorbis.lib",

```

That was not a lot of work to make it compile and kinda run on Linux but there are issues for sure left after that.

**Comment by il8677** [comment]
I've experimented with getting it run on Linux already, but right now I'm just focused on getting it 'turing complete' on windows.

The classes really shouldn't be marked as static, it doesn't do anything, so it can be safely removed. The segfault is probably because the way the grid location is calculated only works on windows right now. I'll investigate it more as soon as the windows version is done (which should be soon).

**Comment by il8677** [comment]
Currently, the code is untested even on windows (there are some vague linker errors), if you still want to get it compiled now, I'd suggest you try a91558a
